services:
  postgres:
    image: postgres:15
    container_name: ledger_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ledgerdb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ledgerdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  ledger-api:
    build: ./ledger-api
    container_name: ledger_api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ledgerdb
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_SECURITY_USER_NAME: ${SECURITY_USERNAME}
      SPRING_SECURITY_USER_PASSWORD: ${SECURITY_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
