services:
  postgres:
    image: postgres:15
    container_name: ledger_postgres
    restart: always
    environment:
      POSTGRES_DB: ledgerdb
      POSTGRES_USER: ledgeruser
      POSTGRES_PASSWORD: ledgerpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledgeruser -d ledgerdb"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: ./ledger-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ledgerdb
      SPRING_DATASOURCE_USERNAME: ledgeruser
      SPRING_DATASOURCE_PASSWORD: ledgerpass
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
